[pytest]
asyncio_mode = strict
filterwarnings =
    ignore::DeprecationWarning:lazy_model.*
    ignore::DeprecationWarning:arq.*
    ignore:.*StarletteDeprecationWarning.*:
    ignore:.*Using `httpx` with `starlette.testclient` is deprecated.*:
